---
stages:
  - docker
  - pre
  - build
  - test
  - coverage
  - analyze
  - deploy

include:
  - .gitlab/common.yml
  - .gitlab/preliminary.yml
  - .gitlab/docker.yml
  - .gitlab/build.yml
  - .gitlab/test_starpu.yml
  - .gitlab/test_starpu_plafrim.yml
  - .gitlab/test_starpu_simgrid.yml
  - .gitlab/test_parsec.yml
  - .gitlab/test_quark.yml
  - .gitlab/test_openmp.yml
  - .gitlab/test_hmat.yml
  - .gitlab/coverage.yml
  - .gitlab/coverity.yml
  - .gitlab/sonarqube.yml
  - .gitlab/bench_plafrim.yml
  - .gitlab/pages.yml
  - .gitlab/release.yml
