---
build_openmp:
  extends: .build_script_template
  artifacts:
    name: build_openmp
    expire_in: 48 hours
    paths:
      - build
      - chameleon_openmp.log
  variables:
    BUILD_OPTIONS: "-DCHAMELEON_SCHED=OPENMP"
    VERSION: openmp

build_parsec:
  extends: .build_script_template
  artifacts:
    name: build_parsec
    expire_in: 48 hours
    paths:
      - build
      - chameleon_parsec.log
  variables:
    BUILD_OPTIONS: "-DCHAMELEON_SCHED=PARSEC"
    VERSION: parsec

build_quark:
  extends: .build_script_template
  artifacts:
    name: build_quark
    expire_in: 48 hours
    paths:
      - build
      - chameleon_quark.log
  variables:
    BUILD_OPTIONS: "-DCHAMELEON_SCHED=QUARK"
    VERSION: quark

build_starpu:
  extends: .build_script_template
  artifacts:
    name: build_starpu
    expire_in: 48 hours
    paths:
      - build
      - chameleon_starpu.log
  variables:
    BUILD_OPTIONS: "-DCHAMELEON_USE_CUDA=ON -DCHAMELEON_USE_MPI=ON"
    VERSION: starpu

build_starpu_simgrid:
  extends: .build_script_template
  artifacts:
    name: build_starpu_simgrid
    expire_in: 48 hours
    paths:
      - build
      - chameleon_starpu_simgrid.log
  variables:
    SIMU: simu
    BUILD_OPTIONS: "-DCHAMELEON_SIMULATION=ON -DCHAMELEON_USE_CUDA=ON -DCHAMELEON_USE_MPI=OFF"
    VERSION: starpu_simgrid

build_all:
  extends: .build_script_template
  artifacts:
    name: build_all
    expire_in: 48 hours
    paths:
      - build
      - chameleon_all.log
  variables:
    BUILD_OPTIONS: "-DCHAMELEON_SCHED_OPENMP=ON -DCHAMELEON_SCHED_PARSEC=ON -DCHAMELEON_SCHED_QUARK=ON -DCHAMELEON_SCHED_STARPU=ON"
    VERSION: all