/**
 *
 * @file chameleon_dlopen.c
 *
 * @copyright 2012-2020 Bordeaux INP, CNRS (LaBRI UMR 5800), Inria,
 *                      Univ. Bordeaux. All rights reserved.
 *
 ***
 *
 * @brief Chameleon control routines
 *
 * @version 1.0.0
 * @author Florent Pruvost
 * @date 2020-08-10
 *
 ***
 *
 * @defgroup Control
 * @brief Group routines exposed to users to control CHAMELEON state
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <dlfcn.h>
#include "control/auxiliary.h"
#include "control/common.h"
#include "chameleon/runtime.h"

/**
 *  Global data
 */
/* dlopen handle */
static void *chameleon_dlopen_handle = NULL;

/**
 * @brief Macro to call dlsym for every runtime symbols
 */
#define RUNTIME_DLSYM( name )                                               \
    *(void**)(&CHAMELEON_##name) = dlsym( chameleon_dlopen_handle, #name ); \
    if ( (error = dlerror()) != NULL ){                                     \
         chameleon_fatal_error("chameleon_dlopen", "dlsym has failed");     \
    }

/**
 * @brief Macro to affect CHAMELEON_INSERT_TASK|RUNTIME functions to
 * INSERT_TASK|RUNTIME ones. Usefull when not using dlopen for chameleon runtime
 * symbols *i.e.* when there is only one chameleon runtime interface enabled at
 * configuration.
 */
#define RUNTIME_AFFECT( name ) CHAMELEON_##name = name;

/**
 *
 * @ingroup Control
 *
 *  @brief chameleon_dlopen - Load the runtime symbols given by the
 *  __CHAMELEON_RUNTIME_LIBRARY__ environment variable.
 *
 * The runtime chosen must be enabled during the Chameleon configuration.
 *
 ******************************************************************************
 *
 */
void chameleon_dlopen()
{
#if defined(CHAMELEON_SCHED_DLOPEN)
    char *error;
    char *cham_runtime_lib_s;

    /* chameleon runtime library must be provided */
    cham_runtime_lib_s = getenv("CHAMELEON_RUNTIME_LIBRARY");
    if ( cham_runtime_lib_s == NULL ){
        chameleon_fatal_error("chameleon_dlopen", "CHAMELEON_RUNTIME_LIBRARY environment variable is not set");
    }

    /* dlopen the given library */
    chameleon_dlopen_handle = dlopen (cham_runtime_lib_s, RTLD_NOW);
    if ( !chameleon_dlopen_handle ){
        fprintf(stderr, "CHAMELEON ERROR: %s dlopen fails\n", cham_runtime_lib_s);
        chameleon_fatal_error("chameleon_dlopen", "dlopen has failed");
    }

    /* load symbols with dlsym */
    RUNTIME_DLSYM( INSERT_TASK_caxpy             )
    RUNTIME_DLSYM( INSERT_TASK_cbuild            )
    RUNTIME_DLSYM( INSERT_TASK_cgeadd            )
    RUNTIME_DLSYM( INSERT_TASK_cgelqt            )
    RUNTIME_DLSYM( INSERT_TASK_cgemm             )
    RUNTIME_DLSYM( INSERT_TASK_cgeqrt            )
    RUNTIME_DLSYM( INSERT_TASK_cgessm            )
    RUNTIME_DLSYM( INSERT_TASK_cgessq            )
    RUNTIME_DLSYM( INSERT_TASK_cgetrf            )
    RUNTIME_DLSYM( INSERT_TASK_cgetrf_incpiv     )
    RUNTIME_DLSYM( INSERT_TASK_cgetrf_nopiv      )
    RUNTIME_DLSYM( INSERT_TASK_cgram             )
    RUNTIME_DLSYM( INSERT_TASK_che2ge            )
    RUNTIME_DLSYM( INSERT_TASK_chemm             )
    RUNTIME_DLSYM( INSERT_TASK_cher2k            )
    RUNTIME_DLSYM( INSERT_TASK_cherfb            )
    RUNTIME_DLSYM( INSERT_TASK_cherk             )
    RUNTIME_DLSYM( INSERT_TASK_chessq            )
    RUNTIME_DLSYM( INSERT_TASK_clacpy            )
    RUNTIME_DLSYM( INSERT_TASK_clacpyx           )
    RUNTIME_DLSYM( INSERT_TASK_clange            )
    RUNTIME_DLSYM( INSERT_TASK_clange_max        )
    RUNTIME_DLSYM( INSERT_TASK_clanhe            )
    RUNTIME_DLSYM( INSERT_TASK_clansy            )
    RUNTIME_DLSYM( INSERT_TASK_clantr            )
    RUNTIME_DLSYM( INSERT_TASK_clascal           )
    RUNTIME_DLSYM( INSERT_TASK_claset            )
    RUNTIME_DLSYM( INSERT_TASK_claset2           )
    RUNTIME_DLSYM( INSERT_TASK_clatro            )
    RUNTIME_DLSYM( INSERT_TASK_clauum            )
    RUNTIME_DLSYM( INSERT_TASK_cplghe            )
    RUNTIME_DLSYM( INSERT_TASK_cplgsy            )
    RUNTIME_DLSYM( INSERT_TASK_cplrnt            )
    RUNTIME_DLSYM( INSERT_TASK_cplssq            )
    RUNTIME_DLSYM( INSERT_TASK_cplssq2           )
    RUNTIME_DLSYM( INSERT_TASK_cpotrf            )
    RUNTIME_DLSYM( INSERT_TASK_cssssm            )
    RUNTIME_DLSYM( INSERT_TASK_csymm             )
    RUNTIME_DLSYM( INSERT_TASK_csyr2k            )
    RUNTIME_DLSYM( INSERT_TASK_csyrk             )
    RUNTIME_DLSYM( INSERT_TASK_csyssq            )
    RUNTIME_DLSYM( INSERT_TASK_csytrf_nopiv      )
    RUNTIME_DLSYM( INSERT_TASK_ctplqt            )
    RUNTIME_DLSYM( INSERT_TASK_ctpmlqt           )
    RUNTIME_DLSYM( INSERT_TASK_ctpmqrt           )
    RUNTIME_DLSYM( INSERT_TASK_ctpqrt            )
    RUNTIME_DLSYM( INSERT_TASK_ctradd            )
    RUNTIME_DLSYM( INSERT_TASK_ctrasm            )
    RUNTIME_DLSYM( INSERT_TASK_ctrmm             )
    RUNTIME_DLSYM( INSERT_TASK_ctrsm             )
    RUNTIME_DLSYM( INSERT_TASK_ctrssq            )
    RUNTIME_DLSYM( INSERT_TASK_ctrtri            )
    RUNTIME_DLSYM( INSERT_TASK_ctsmlq_hetra1     )
    RUNTIME_DLSYM( INSERT_TASK_ctsmqr_hetra1     )
    RUNTIME_DLSYM( INSERT_TASK_ctstrf            )
    RUNTIME_DLSYM( INSERT_TASK_cunmlq            )
    RUNTIME_DLSYM( INSERT_TASK_cunmqr            )
    RUNTIME_DLSYM( INSERT_TASK_dasum             )
    RUNTIME_DLSYM( INSERT_TASK_daxpy             )
    RUNTIME_DLSYM( INSERT_TASK_dbuild            )
    RUNTIME_DLSYM( INSERT_TASK_dgeadd            )
    RUNTIME_DLSYM( INSERT_TASK_dgelqt            )
    RUNTIME_DLSYM( INSERT_TASK_dgemm             )
    RUNTIME_DLSYM( INSERT_TASK_dgeqrt            )
    RUNTIME_DLSYM( INSERT_TASK_dgessm            )
    RUNTIME_DLSYM( INSERT_TASK_dgessq            )
    RUNTIME_DLSYM( INSERT_TASK_dgetrf            )
    RUNTIME_DLSYM( INSERT_TASK_dgetrf_incpiv     )
    RUNTIME_DLSYM( INSERT_TASK_dgetrf_nopiv      )
    RUNTIME_DLSYM( INSERT_TASK_dgram             )
    RUNTIME_DLSYM( INSERT_TASK_dhe2ge            )
    RUNTIME_DLSYM( INSERT_TASK_dlacpy            )
    RUNTIME_DLSYM( INSERT_TASK_dlacpyx           )
    RUNTIME_DLSYM( INSERT_TASK_dlange            )
    RUNTIME_DLSYM( INSERT_TASK_dlange_max        )
    RUNTIME_DLSYM( INSERT_TASK_dlansy            )
    RUNTIME_DLSYM( INSERT_TASK_dlantr            )
    RUNTIME_DLSYM( INSERT_TASK_dlascal           )
    RUNTIME_DLSYM( INSERT_TASK_dlaset            )
    RUNTIME_DLSYM( INSERT_TASK_dlaset2           )
    RUNTIME_DLSYM( INSERT_TASK_dlatro            )
    RUNTIME_DLSYM( INSERT_TASK_dlauum            )
    RUNTIME_DLSYM( INSERT_TASK_dormlq            )
    RUNTIME_DLSYM( INSERT_TASK_dormqr            )
    RUNTIME_DLSYM( INSERT_TASK_dplgsy            )
    RUNTIME_DLSYM( INSERT_TASK_dplrnt            )
    RUNTIME_DLSYM( INSERT_TASK_dplssq            )
    RUNTIME_DLSYM( INSERT_TASK_dplssq2           )
    RUNTIME_DLSYM( INSERT_TASK_dpotrf            )
    RUNTIME_DLSYM( INSERT_TASK_dssssm            )
    RUNTIME_DLSYM( INSERT_TASK_dsymm             )
    RUNTIME_DLSYM( INSERT_TASK_dsyr2k            )
    RUNTIME_DLSYM( INSERT_TASK_dsyrfb            )
    RUNTIME_DLSYM( INSERT_TASK_dsyrk             )
    RUNTIME_DLSYM( INSERT_TASK_dsyssq            )
    RUNTIME_DLSYM( INSERT_TASK_dtplqt            )
    RUNTIME_DLSYM( INSERT_TASK_dtpmlqt           )
    RUNTIME_DLSYM( INSERT_TASK_dtpmqrt           )
    RUNTIME_DLSYM( INSERT_TASK_dtpqrt            )
    RUNTIME_DLSYM( INSERT_TASK_dtradd            )
    RUNTIME_DLSYM( INSERT_TASK_dtrasm            )
    RUNTIME_DLSYM( INSERT_TASK_dtrmm             )
    RUNTIME_DLSYM( INSERT_TASK_dtrsm             )
    RUNTIME_DLSYM( INSERT_TASK_dtrssq            )
    RUNTIME_DLSYM( INSERT_TASK_dtrtri            )
    RUNTIME_DLSYM( INSERT_TASK_dtsmlq_hetra1     )
    RUNTIME_DLSYM( INSERT_TASK_dtsmqr_hetra1     )
    RUNTIME_DLSYM( INSERT_TASK_dtstrf            )
    RUNTIME_DLSYM( INSERT_TASK_dzasum            )
    RUNTIME_DLSYM( INSERT_TASK_map               )
    RUNTIME_DLSYM( INSERT_TASK_sasum             )
    RUNTIME_DLSYM( INSERT_TASK_saxpy             )
    RUNTIME_DLSYM( INSERT_TASK_sbuild            )
    RUNTIME_DLSYM( INSERT_TASK_scasum            )
    RUNTIME_DLSYM( INSERT_TASK_sgeadd            )
    RUNTIME_DLSYM( INSERT_TASK_sgelqt            )
    RUNTIME_DLSYM( INSERT_TASK_sgemm             )
    RUNTIME_DLSYM( INSERT_TASK_sgeqrt            )
    RUNTIME_DLSYM( INSERT_TASK_sgessm            )
    RUNTIME_DLSYM( INSERT_TASK_sgessq            )
    RUNTIME_DLSYM( INSERT_TASK_sgetrf            )
    RUNTIME_DLSYM( INSERT_TASK_sgetrf_incpiv     )
    RUNTIME_DLSYM( INSERT_TASK_sgetrf_nopiv      )
    RUNTIME_DLSYM( INSERT_TASK_sgram             )
    RUNTIME_DLSYM( INSERT_TASK_she2ge            )
    RUNTIME_DLSYM( INSERT_TASK_slacpy            )
    RUNTIME_DLSYM( INSERT_TASK_slacpyx           )
    RUNTIME_DLSYM( INSERT_TASK_slange            )
    RUNTIME_DLSYM( INSERT_TASK_slange_max        )
    RUNTIME_DLSYM( INSERT_TASK_slansy            )
    RUNTIME_DLSYM( INSERT_TASK_slantr            )
    RUNTIME_DLSYM( INSERT_TASK_slascal           )
    RUNTIME_DLSYM( INSERT_TASK_slaset            )
    RUNTIME_DLSYM( INSERT_TASK_slaset2           )
    RUNTIME_DLSYM( INSERT_TASK_slatro            )
    RUNTIME_DLSYM( INSERT_TASK_slauum            )
    RUNTIME_DLSYM( INSERT_TASK_sormlq            )
    RUNTIME_DLSYM( INSERT_TASK_sormqr            )
    RUNTIME_DLSYM( INSERT_TASK_splgsy            )
    RUNTIME_DLSYM( INSERT_TASK_splrnt            )
    RUNTIME_DLSYM( INSERT_TASK_splssq            )
    RUNTIME_DLSYM( INSERT_TASK_splssq2           )
    RUNTIME_DLSYM( INSERT_TASK_spotrf            )
    RUNTIME_DLSYM( INSERT_TASK_sssssm            )
    RUNTIME_DLSYM( INSERT_TASK_ssymm             )
    RUNTIME_DLSYM( INSERT_TASK_ssyr2k            )
    RUNTIME_DLSYM( INSERT_TASK_ssyrfb            )
    RUNTIME_DLSYM( INSERT_TASK_ssyrk             )
    RUNTIME_DLSYM( INSERT_TASK_ssyssq            )
    RUNTIME_DLSYM( INSERT_TASK_stplqt            )
    RUNTIME_DLSYM( INSERT_TASK_stpmlqt           )
    RUNTIME_DLSYM( INSERT_TASK_stpmqrt           )
    RUNTIME_DLSYM( INSERT_TASK_stpqrt            )
    RUNTIME_DLSYM( INSERT_TASK_stradd            )
    RUNTIME_DLSYM( INSERT_TASK_strasm            )
    RUNTIME_DLSYM( INSERT_TASK_strmm             )
    RUNTIME_DLSYM( INSERT_TASK_strsm             )
    RUNTIME_DLSYM( INSERT_TASK_strssq            )
    RUNTIME_DLSYM( INSERT_TASK_strtri            )
    RUNTIME_DLSYM( INSERT_TASK_stsmlq_hetra1     )
    RUNTIME_DLSYM( INSERT_TASK_stsmqr_hetra1     )
    RUNTIME_DLSYM( INSERT_TASK_ststrf            )
    RUNTIME_DLSYM( INSERT_TASK_zaxpy             )
    RUNTIME_DLSYM( INSERT_TASK_zbuild            )
    RUNTIME_DLSYM( INSERT_TASK_zgeadd            )
    RUNTIME_DLSYM( INSERT_TASK_zgelqt            )
    RUNTIME_DLSYM( INSERT_TASK_zgemm             )
    RUNTIME_DLSYM( INSERT_TASK_zgeqrt            )
    RUNTIME_DLSYM( INSERT_TASK_zgessm            )
    RUNTIME_DLSYM( INSERT_TASK_zgessq            )
    RUNTIME_DLSYM( INSERT_TASK_zgetrf            )
    RUNTIME_DLSYM( INSERT_TASK_zgetrf_incpiv     )
    RUNTIME_DLSYM( INSERT_TASK_zgetrf_nopiv      )
    RUNTIME_DLSYM( INSERT_TASK_zgram             )
    RUNTIME_DLSYM( INSERT_TASK_zhe2ge            )
    RUNTIME_DLSYM( INSERT_TASK_zhemm             )
    RUNTIME_DLSYM( INSERT_TASK_zher2k            )
    RUNTIME_DLSYM( INSERT_TASK_zherfb            )
    RUNTIME_DLSYM( INSERT_TASK_zherk             )
    RUNTIME_DLSYM( INSERT_TASK_zhessq            )
    RUNTIME_DLSYM( INSERT_TASK_zlacpy            )
    RUNTIME_DLSYM( INSERT_TASK_zlacpyx           )
    RUNTIME_DLSYM( INSERT_TASK_zlange            )
    RUNTIME_DLSYM( INSERT_TASK_zlange_max        )
    RUNTIME_DLSYM( INSERT_TASK_zlanhe            )
    RUNTIME_DLSYM( INSERT_TASK_zlansy            )
    RUNTIME_DLSYM( INSERT_TASK_zlantr            )
    RUNTIME_DLSYM( INSERT_TASK_zlascal           )
    RUNTIME_DLSYM( INSERT_TASK_zlaset            )
    RUNTIME_DLSYM( INSERT_TASK_zlaset2           )
    RUNTIME_DLSYM( INSERT_TASK_zlatro            )
    RUNTIME_DLSYM( INSERT_TASK_zlauum            )
    RUNTIME_DLSYM( INSERT_TASK_zplghe            )
    RUNTIME_DLSYM( INSERT_TASK_zplgsy            )
    RUNTIME_DLSYM( INSERT_TASK_zplrnt            )
    RUNTIME_DLSYM( INSERT_TASK_zplssq            )
    RUNTIME_DLSYM( INSERT_TASK_zplssq2           )
    RUNTIME_DLSYM( INSERT_TASK_zpotrf            )
    RUNTIME_DLSYM( INSERT_TASK_zssssm            )
    RUNTIME_DLSYM( INSERT_TASK_zsymm             )
    RUNTIME_DLSYM( INSERT_TASK_zsyr2k            )
    RUNTIME_DLSYM( INSERT_TASK_zsyrk             )
    RUNTIME_DLSYM( INSERT_TASK_zsyssq            )
    RUNTIME_DLSYM( INSERT_TASK_zsytrf_nopiv      )
    RUNTIME_DLSYM( INSERT_TASK_ztplqt            )
    RUNTIME_DLSYM( INSERT_TASK_ztpmlqt           )
    RUNTIME_DLSYM( INSERT_TASK_ztpmqrt           )
    RUNTIME_DLSYM( INSERT_TASK_ztpqrt            )
    RUNTIME_DLSYM( INSERT_TASK_ztradd            )
    RUNTIME_DLSYM( INSERT_TASK_ztrasm            )
    RUNTIME_DLSYM( INSERT_TASK_ztrmm             )
    RUNTIME_DLSYM( INSERT_TASK_ztrsm             )
    RUNTIME_DLSYM( INSERT_TASK_ztrssq            )
    RUNTIME_DLSYM( INSERT_TASK_ztrtri            )
    RUNTIME_DLSYM( INSERT_TASK_ztsmlq_hetra1     )
    RUNTIME_DLSYM( INSERT_TASK_ztsmqr_hetra1     )
    RUNTIME_DLSYM( INSERT_TASK_ztstrf            )
    RUNTIME_DLSYM( INSERT_TASK_zunmlq            )
    RUNTIME_DLSYM( INSERT_TASK_zunmqr            )
    RUNTIME_DLSYM( RUNTIME_barrier               )
    RUNTIME_DLSYM( RUNTIME_comm_rank             )
    RUNTIME_DLSYM( RUNTIME_comm_set_tag_sizes    )
    RUNTIME_DLSYM( RUNTIME_comm_size             )
    RUNTIME_DLSYM( RUNTIME_context_create        )
    RUNTIME_DLSYM( RUNTIME_context_destroy       )
    RUNTIME_DLSYM( RUNTIME_data_flush            )
#if defined(CHAMELEON_USE_MIGRATE)
    RUNTIME_DLSYM( RUNTIME_data_migrate          )
#endif
    RUNTIME_DLSYM( RUNTIME_desc_acquire          )
    RUNTIME_DLSYM( RUNTIME_desc_create           )
    RUNTIME_DLSYM( RUNTIME_desc_destroy          )
    RUNTIME_DLSYM( RUNTIME_desc_flush            )
    RUNTIME_DLSYM( RUNTIME_desc_release          )
    RUNTIME_DLSYM( RUNTIME_disable               )
    RUNTIME_DLSYM( RUNTIME_enable                )
    RUNTIME_DLSYM( RUNTIME_finalize              )
    RUNTIME_DLSYM( RUNTIME_flush                 )
    RUNTIME_DLSYM( RUNTIME_free                  )
    RUNTIME_DLSYM( RUNTIME_get_time              )
    RUNTIME_DLSYM( RUNTIME_init                  )
    RUNTIME_DLSYM( RUNTIME_iteration_pop         )
    RUNTIME_DLSYM( RUNTIME_iteration_push        )
    RUNTIME_DLSYM( RUNTIME_kernelprofile_display )
    RUNTIME_DLSYM( RUNTIME_malloc                )
    RUNTIME_DLSYM( RUNTIME_options_finalize      )
    RUNTIME_DLSYM( RUNTIME_options_init          )
    RUNTIME_DLSYM( RUNTIME_options_ws_alloc      )
    RUNTIME_DLSYM( RUNTIME_options_ws_free       )
    RUNTIME_DLSYM( RUNTIME_pause                 )
    RUNTIME_DLSYM( RUNTIME_progress              )
    RUNTIME_DLSYM( RUNTIME_request_create        )
    RUNTIME_DLSYM( RUNTIME_request_destroy       )
    RUNTIME_DLSYM( RUNTIME_request_set           )
    RUNTIME_DLSYM( RUNTIME_resume                )
    RUNTIME_DLSYM( RUNTIME_schedprofile_display  )
    RUNTIME_DLSYM( RUNTIME_sequence_create       )
    RUNTIME_DLSYM( RUNTIME_sequence_destroy      )
    RUNTIME_DLSYM( RUNTIME_sequence_flush        )
    RUNTIME_DLSYM( RUNTIME_sequence_wait         )
    RUNTIME_DLSYM( RUNTIME_start_profiling       )
    RUNTIME_DLSYM( RUNTIME_start_stats           )
    RUNTIME_DLSYM( RUNTIME_stop_profiling        )
    RUNTIME_DLSYM( RUNTIME_stop_stats            )
    RUNTIME_DLSYM( RUNTIME_thread_rank           )
    RUNTIME_DLSYM( RUNTIME_thread_size           )
#else
    RUNTIME_AFFECT( INSERT_TASK_caxpy             )
    RUNTIME_AFFECT( INSERT_TASK_cbuild            )
    RUNTIME_AFFECT( INSERT_TASK_cgeadd            )
    RUNTIME_AFFECT( INSERT_TASK_cgelqt            )
    RUNTIME_AFFECT( INSERT_TASK_cgemm             )
    RUNTIME_AFFECT( INSERT_TASK_cgeqrt            )
    RUNTIME_AFFECT( INSERT_TASK_cgessm            )
    RUNTIME_AFFECT( INSERT_TASK_cgessq            )
    RUNTIME_AFFECT( INSERT_TASK_cgetrf            )
    RUNTIME_AFFECT( INSERT_TASK_cgetrf_incpiv     )
    RUNTIME_AFFECT( INSERT_TASK_cgetrf_nopiv      )
    RUNTIME_AFFECT( INSERT_TASK_cgram             )
    RUNTIME_AFFECT( INSERT_TASK_che2ge            )
    RUNTIME_AFFECT( INSERT_TASK_chemm             )
    RUNTIME_AFFECT( INSERT_TASK_cher2k            )
    RUNTIME_AFFECT( INSERT_TASK_cherfb            )
    RUNTIME_AFFECT( INSERT_TASK_cherk             )
    RUNTIME_AFFECT( INSERT_TASK_chessq            )
    RUNTIME_AFFECT( INSERT_TASK_clacpy            )
    RUNTIME_AFFECT( INSERT_TASK_clacpyx           )
    RUNTIME_AFFECT( INSERT_TASK_clange            )
    RUNTIME_AFFECT( INSERT_TASK_clange_max        )
    RUNTIME_AFFECT( INSERT_TASK_clanhe            )
    RUNTIME_AFFECT( INSERT_TASK_clansy            )
    RUNTIME_AFFECT( INSERT_TASK_clantr            )
    RUNTIME_AFFECT( INSERT_TASK_clascal           )
    RUNTIME_AFFECT( INSERT_TASK_claset            )
    RUNTIME_AFFECT( INSERT_TASK_claset2           )
    RUNTIME_AFFECT( INSERT_TASK_clatro            )
    RUNTIME_AFFECT( INSERT_TASK_clauum            )
    RUNTIME_AFFECT( INSERT_TASK_cplghe            )
    RUNTIME_AFFECT( INSERT_TASK_cplgsy            )
    RUNTIME_AFFECT( INSERT_TASK_cplrnt            )
    RUNTIME_AFFECT( INSERT_TASK_cplssq            )
    RUNTIME_AFFECT( INSERT_TASK_cplssq2           )
    RUNTIME_AFFECT( INSERT_TASK_cpotrf            )
    RUNTIME_AFFECT( INSERT_TASK_cssssm            )
    RUNTIME_AFFECT( INSERT_TASK_csymm             )
    RUNTIME_AFFECT( INSERT_TASK_csyr2k            )
    RUNTIME_AFFECT( INSERT_TASK_csyrk             )
    RUNTIME_AFFECT( INSERT_TASK_csyssq            )
    RUNTIME_AFFECT( INSERT_TASK_csytrf_nopiv      )
    RUNTIME_AFFECT( INSERT_TASK_ctplqt            )
    RUNTIME_AFFECT( INSERT_TASK_ctpmlqt           )
    RUNTIME_AFFECT( INSERT_TASK_ctpmqrt           )
    RUNTIME_AFFECT( INSERT_TASK_ctpqrt            )
    RUNTIME_AFFECT( INSERT_TASK_ctradd            )
    RUNTIME_AFFECT( INSERT_TASK_ctrasm            )
    RUNTIME_AFFECT( INSERT_TASK_ctrmm             )
    RUNTIME_AFFECT( INSERT_TASK_ctrsm             )
    RUNTIME_AFFECT( INSERT_TASK_ctrssq            )
    RUNTIME_AFFECT( INSERT_TASK_ctrtri            )
    RUNTIME_AFFECT( INSERT_TASK_ctsmlq_hetra1     )
    RUNTIME_AFFECT( INSERT_TASK_ctsmqr_hetra1     )
    RUNTIME_AFFECT( INSERT_TASK_ctstrf            )
    RUNTIME_AFFECT( INSERT_TASK_cunmlq            )
    RUNTIME_AFFECT( INSERT_TASK_cunmqr            )
    RUNTIME_AFFECT( INSERT_TASK_dasum             )
    RUNTIME_AFFECT( INSERT_TASK_daxpy             )
    RUNTIME_AFFECT( INSERT_TASK_dbuild            )
    RUNTIME_AFFECT( INSERT_TASK_dgeadd            )
    RUNTIME_AFFECT( INSERT_TASK_dgelqt            )
    RUNTIME_AFFECT( INSERT_TASK_dgemm             )
    RUNTIME_AFFECT( INSERT_TASK_dgeqrt            )
    RUNTIME_AFFECT( INSERT_TASK_dgessm            )
    RUNTIME_AFFECT( INSERT_TASK_dgessq            )
    RUNTIME_AFFECT( INSERT_TASK_dgetrf            )
    RUNTIME_AFFECT( INSERT_TASK_dgetrf_incpiv     )
    RUNTIME_AFFECT( INSERT_TASK_dgetrf_nopiv      )
    RUNTIME_AFFECT( INSERT_TASK_dgram             )
    RUNTIME_AFFECT( INSERT_TASK_dhe2ge            )
    RUNTIME_AFFECT( INSERT_TASK_dlacpy            )
    RUNTIME_AFFECT( INSERT_TASK_dlacpyx           )
    RUNTIME_AFFECT( INSERT_TASK_dlange            )
    RUNTIME_AFFECT( INSERT_TASK_dlange_max        )
    RUNTIME_AFFECT( INSERT_TASK_dlansy            )
    RUNTIME_AFFECT( INSERT_TASK_dlantr            )
    RUNTIME_AFFECT( INSERT_TASK_dlascal           )
    RUNTIME_AFFECT( INSERT_TASK_dlaset            )
    RUNTIME_AFFECT( INSERT_TASK_dlaset2           )
    RUNTIME_AFFECT( INSERT_TASK_dlatro            )
    RUNTIME_AFFECT( INSERT_TASK_dlauum            )
    RUNTIME_AFFECT( INSERT_TASK_dormlq            )
    RUNTIME_AFFECT( INSERT_TASK_dormqr            )
    RUNTIME_AFFECT( INSERT_TASK_dplgsy            )
    RUNTIME_AFFECT( INSERT_TASK_dplrnt            )
    RUNTIME_AFFECT( INSERT_TASK_dplssq            )
    RUNTIME_AFFECT( INSERT_TASK_dplssq2           )
    RUNTIME_AFFECT( INSERT_TASK_dpotrf            )
    RUNTIME_AFFECT( INSERT_TASK_dssssm            )
    RUNTIME_AFFECT( INSERT_TASK_dsymm             )
    RUNTIME_AFFECT( INSERT_TASK_dsyr2k            )
    RUNTIME_AFFECT( INSERT_TASK_dsyrfb            )
    RUNTIME_AFFECT( INSERT_TASK_dsyrk             )
    RUNTIME_AFFECT( INSERT_TASK_dsyssq            )
    RUNTIME_AFFECT( INSERT_TASK_dtplqt            )
    RUNTIME_AFFECT( INSERT_TASK_dtpmlqt           )
    RUNTIME_AFFECT( INSERT_TASK_dtpmqrt           )
    RUNTIME_AFFECT( INSERT_TASK_dtpqrt            )
    RUNTIME_AFFECT( INSERT_TASK_dtradd            )
    RUNTIME_AFFECT( INSERT_TASK_dtrasm            )
    RUNTIME_AFFECT( INSERT_TASK_dtrmm             )
    RUNTIME_AFFECT( INSERT_TASK_dtrsm             )
    RUNTIME_AFFECT( INSERT_TASK_dtrssq            )
    RUNTIME_AFFECT( INSERT_TASK_dtrtri            )
    RUNTIME_AFFECT( INSERT_TASK_dtsmlq_hetra1     )
    RUNTIME_AFFECT( INSERT_TASK_dtsmqr_hetra1     )
    RUNTIME_AFFECT( INSERT_TASK_dtstrf            )
    RUNTIME_AFFECT( INSERT_TASK_dzasum            )
    RUNTIME_AFFECT( INSERT_TASK_map               )
    RUNTIME_AFFECT( INSERT_TASK_sasum             )
    RUNTIME_AFFECT( INSERT_TASK_saxpy             )
    RUNTIME_AFFECT( INSERT_TASK_sbuild            )
    RUNTIME_AFFECT( INSERT_TASK_scasum            )
    RUNTIME_AFFECT( INSERT_TASK_sgeadd            )
    RUNTIME_AFFECT( INSERT_TASK_sgelqt            )
    RUNTIME_AFFECT( INSERT_TASK_sgemm             )
    RUNTIME_AFFECT( INSERT_TASK_sgeqrt            )
    RUNTIME_AFFECT( INSERT_TASK_sgessm            )
    RUNTIME_AFFECT( INSERT_TASK_sgessq            )
    RUNTIME_AFFECT( INSERT_TASK_sgetrf            )
    RUNTIME_AFFECT( INSERT_TASK_sgetrf_incpiv     )
    RUNTIME_AFFECT( INSERT_TASK_sgetrf_nopiv      )
    RUNTIME_AFFECT( INSERT_TASK_sgram             )
    RUNTIME_AFFECT( INSERT_TASK_she2ge            )
    RUNTIME_AFFECT( INSERT_TASK_slacpy            )
    RUNTIME_AFFECT( INSERT_TASK_slacpyx           )
    RUNTIME_AFFECT( INSERT_TASK_slange            )
    RUNTIME_AFFECT( INSERT_TASK_slange_max        )
    RUNTIME_AFFECT( INSERT_TASK_slansy            )
    RUNTIME_AFFECT( INSERT_TASK_slantr            )
    RUNTIME_AFFECT( INSERT_TASK_slascal           )
    RUNTIME_AFFECT( INSERT_TASK_slaset            )
    RUNTIME_AFFECT( INSERT_TASK_slaset2           )
    RUNTIME_AFFECT( INSERT_TASK_slatro            )
    RUNTIME_AFFECT( INSERT_TASK_slauum            )
    RUNTIME_AFFECT( INSERT_TASK_sormlq            )
    RUNTIME_AFFECT( INSERT_TASK_sormqr            )
    RUNTIME_AFFECT( INSERT_TASK_splgsy            )
    RUNTIME_AFFECT( INSERT_TASK_splrnt            )
    RUNTIME_AFFECT( INSERT_TASK_splssq            )
    RUNTIME_AFFECT( INSERT_TASK_splssq2           )
    RUNTIME_AFFECT( INSERT_TASK_spotrf            )
    RUNTIME_AFFECT( INSERT_TASK_sssssm            )
    RUNTIME_AFFECT( INSERT_TASK_ssymm             )
    RUNTIME_AFFECT( INSERT_TASK_ssyr2k            )
    RUNTIME_AFFECT( INSERT_TASK_ssyrfb            )
    RUNTIME_AFFECT( INSERT_TASK_ssyrk             )
    RUNTIME_AFFECT( INSERT_TASK_ssyssq            )
    RUNTIME_AFFECT( INSERT_TASK_stplqt            )
    RUNTIME_AFFECT( INSERT_TASK_stpmlqt           )
    RUNTIME_AFFECT( INSERT_TASK_stpmqrt           )
    RUNTIME_AFFECT( INSERT_TASK_stpqrt            )
    RUNTIME_AFFECT( INSERT_TASK_stradd            )
    RUNTIME_AFFECT( INSERT_TASK_strasm            )
    RUNTIME_AFFECT( INSERT_TASK_strmm             )
    RUNTIME_AFFECT( INSERT_TASK_strsm             )
    RUNTIME_AFFECT( INSERT_TASK_strssq            )
    RUNTIME_AFFECT( INSERT_TASK_strtri            )
    RUNTIME_AFFECT( INSERT_TASK_stsmlq_hetra1     )
    RUNTIME_AFFECT( INSERT_TASK_stsmqr_hetra1     )
    RUNTIME_AFFECT( INSERT_TASK_ststrf            )
    RUNTIME_AFFECT( INSERT_TASK_zaxpy             )
    RUNTIME_AFFECT( INSERT_TASK_zbuild            )
    RUNTIME_AFFECT( INSERT_TASK_zgeadd            )
    RUNTIME_AFFECT( INSERT_TASK_zgelqt            )
    RUNTIME_AFFECT( INSERT_TASK_zgemm             )
    RUNTIME_AFFECT( INSERT_TASK_zgeqrt            )
    RUNTIME_AFFECT( INSERT_TASK_zgessm            )
    RUNTIME_AFFECT( INSERT_TASK_zgessq            )
    RUNTIME_AFFECT( INSERT_TASK_zgetrf            )
    RUNTIME_AFFECT( INSERT_TASK_zgetrf_incpiv     )
    RUNTIME_AFFECT( INSERT_TASK_zgetrf_nopiv      )
    RUNTIME_AFFECT( INSERT_TASK_zgram             )
    RUNTIME_AFFECT( INSERT_TASK_zhe2ge            )
    RUNTIME_AFFECT( INSERT_TASK_zhemm             )
    RUNTIME_AFFECT( INSERT_TASK_zher2k            )
    RUNTIME_AFFECT( INSERT_TASK_zherfb            )
    RUNTIME_AFFECT( INSERT_TASK_zherk             )
    RUNTIME_AFFECT( INSERT_TASK_zhessq            )
    RUNTIME_AFFECT( INSERT_TASK_zlacpy            )
    RUNTIME_AFFECT( INSERT_TASK_zlacpyx           )
    RUNTIME_AFFECT( INSERT_TASK_zlange            )
    RUNTIME_AFFECT( INSERT_TASK_zlange_max        )
    RUNTIME_AFFECT( INSERT_TASK_zlanhe            )
    RUNTIME_AFFECT( INSERT_TASK_zlansy            )
    RUNTIME_AFFECT( INSERT_TASK_zlantr            )
    RUNTIME_AFFECT( INSERT_TASK_zlascal           )
    RUNTIME_AFFECT( INSERT_TASK_zlaset            )
    RUNTIME_AFFECT( INSERT_TASK_zlaset2           )
    RUNTIME_AFFECT( INSERT_TASK_zlatro            )
    RUNTIME_AFFECT( INSERT_TASK_zlauum            )
    RUNTIME_AFFECT( INSERT_TASK_zplghe            )
    RUNTIME_AFFECT( INSERT_TASK_zplgsy            )
    RUNTIME_AFFECT( INSERT_TASK_zplrnt            )
    RUNTIME_AFFECT( INSERT_TASK_zplssq            )
    RUNTIME_AFFECT( INSERT_TASK_zplssq2           )
    RUNTIME_AFFECT( INSERT_TASK_zpotrf            )
    RUNTIME_AFFECT( INSERT_TASK_zssssm            )
    RUNTIME_AFFECT( INSERT_TASK_zsymm             )
    RUNTIME_AFFECT( INSERT_TASK_zsyr2k            )
    RUNTIME_AFFECT( INSERT_TASK_zsyrk             )
    RUNTIME_AFFECT( INSERT_TASK_zsyssq            )
    RUNTIME_AFFECT( INSERT_TASK_zsytrf_nopiv      )
    RUNTIME_AFFECT( INSERT_TASK_ztplqt            )
    RUNTIME_AFFECT( INSERT_TASK_ztpmlqt           )
    RUNTIME_AFFECT( INSERT_TASK_ztpmqrt           )
    RUNTIME_AFFECT( INSERT_TASK_ztpqrt            )
    RUNTIME_AFFECT( INSERT_TASK_ztradd            )
    RUNTIME_AFFECT( INSERT_TASK_ztrasm            )
    RUNTIME_AFFECT( INSERT_TASK_ztrmm             )
    RUNTIME_AFFECT( INSERT_TASK_ztrsm             )
    RUNTIME_AFFECT( INSERT_TASK_ztrssq            )
    RUNTIME_AFFECT( INSERT_TASK_ztrtri            )
    RUNTIME_AFFECT( INSERT_TASK_ztsmlq_hetra1     )
    RUNTIME_AFFECT( INSERT_TASK_ztsmqr_hetra1     )
    RUNTIME_AFFECT( INSERT_TASK_ztstrf            )
    RUNTIME_AFFECT( INSERT_TASK_zunmlq            )
    RUNTIME_AFFECT( INSERT_TASK_zunmqr            )
    RUNTIME_AFFECT( RUNTIME_barrier               )
    RUNTIME_AFFECT( RUNTIME_comm_rank             )
    RUNTIME_AFFECT( RUNTIME_comm_set_tag_sizes    )
    RUNTIME_AFFECT( RUNTIME_comm_size             )
    RUNTIME_AFFECT( RUNTIME_context_create        )
    RUNTIME_AFFECT( RUNTIME_context_destroy       )
    RUNTIME_AFFECT( RUNTIME_data_flush            )
#if defined(CHAMELEON_USE_MIGRATE)
    RUNTIME_AFFECT( RUNTIME_data_migrate          )
#endif
    RUNTIME_AFFECT( RUNTIME_desc_acquire          )
    RUNTIME_AFFECT( RUNTIME_desc_create           )
    RUNTIME_AFFECT( RUNTIME_desc_destroy          )
    RUNTIME_AFFECT( RUNTIME_desc_flush            )
    RUNTIME_AFFECT( RUNTIME_desc_release          )
    RUNTIME_AFFECT( RUNTIME_disable               )
    RUNTIME_AFFECT( RUNTIME_enable                )
    RUNTIME_AFFECT( RUNTIME_finalize              )
    RUNTIME_AFFECT( RUNTIME_flush                 )
    RUNTIME_AFFECT( RUNTIME_free                  )
    RUNTIME_AFFECT( RUNTIME_get_time              )
    RUNTIME_AFFECT( RUNTIME_init                  )
    RUNTIME_AFFECT( RUNTIME_iteration_pop         )
    RUNTIME_AFFECT( RUNTIME_iteration_push        )
    RUNTIME_AFFECT( RUNTIME_kernelprofile_display )
    RUNTIME_AFFECT( RUNTIME_malloc                )
    RUNTIME_AFFECT( RUNTIME_options_finalize      )
    RUNTIME_AFFECT( RUNTIME_options_init          )
    RUNTIME_AFFECT( RUNTIME_options_ws_alloc      )
    RUNTIME_AFFECT( RUNTIME_options_ws_free       )
    RUNTIME_AFFECT( RUNTIME_pause                 )
    RUNTIME_AFFECT( RUNTIME_progress              )
    RUNTIME_AFFECT( RUNTIME_request_create        )
    RUNTIME_AFFECT( RUNTIME_request_destroy       )
    RUNTIME_AFFECT( RUNTIME_request_set           )
    RUNTIME_AFFECT( RUNTIME_resume                )
    RUNTIME_AFFECT( RUNTIME_schedprofile_display  )
    RUNTIME_AFFECT( RUNTIME_sequence_create       )
    RUNTIME_AFFECT( RUNTIME_sequence_destroy      )
    RUNTIME_AFFECT( RUNTIME_sequence_flush        )
    RUNTIME_AFFECT( RUNTIME_sequence_wait         )
    RUNTIME_AFFECT( RUNTIME_start_profiling       )
    RUNTIME_AFFECT( RUNTIME_start_stats           )
    RUNTIME_AFFECT( RUNTIME_stop_profiling        )
    RUNTIME_AFFECT( RUNTIME_stop_stats            )
    RUNTIME_AFFECT( RUNTIME_thread_rank           )
    RUNTIME_AFFECT( RUNTIME_thread_size           )
#endif
    return;
}

void chameleon_dlclose()
{
#if defined(CHAMELEON_SCHED_DLOPEN)
    dlclose(chameleon_dlopen_handle);
#endif
}